
// File generated by the Firebase CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // As we are only targeting web for now, we can throw an error for other platforms.
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqLeKYrM067KpyS8Fxa2nv2MCHh51pexE',
    appId: '1:178879481903:web:54e0dbb5565c96e8e99eda',
    messagingSenderId: '178879481903',
    projectId: 'firebasetestcreate',
    authDomain: 'fir-testcreate-f07ea.firebaseapp.com',
    storageBucket: 'firebasetestcreate.firebasestorage.app',
  );
}
